blank_issues_enabled: false
contact_links:
  - name: Radiant Lyrics Support Server
    url: https://tidal.gg/EsNDvBaHVU
    about: If you need help regarding Radiant Lyrics or plugins for Radiant Lyrics, please join our support server.
