name: Build Release App

on:
  workflow_call:
    secrets:
      keyAlias:
        required: true
      keyPassword:
        required: true
      keystorePassword:
        required: true
      keystore:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: zulu

      - uses: gradle/actions/setup-gradle@v4

      - name: Build
        working-directory: Manager
        env:
          SIGNING_KEY_ALIAS: ${{ secrets.keyAlias }}
          SIGNING_KEY_PASSWORD: ${{ secrets.keyPassword }}
          SIGNING_STORE_PASSWORD: ${{ secrets.keystorePassword }}
          SIGNING_STORE_FILE: ${{ github.workspace }}/release.keystore
          RELEASE: true
        run: |
          echo "${{ secrets.keystore }}" | base64 -d > ${{ github.workspace }}/release.keystore
          ./gradlew :app:packageRelease --stacktrace
          rm ${{ github.workspace }}/release.keystore

      - uses: actions/upload-artifact@v4
        with:
          name: rl-mobile-artifacts
          if-no-files-found: error
          path: Manager/app/build/outputs/apk/release/app-release.apk
