name: "[main] Release"

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**/*.md"

jobs:
  Build:
    uses: ./.github/workflows/build.yml
    secrets: inherit

  Release:
    name: Publish Release
    needs: Build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: rl-mobile-artifacts
          path: ./dist/

      - name: Rename APK
        run: mv ./dist/app-release.apk ./dist/rl-manager.apk

      - name: Publish release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: latest
          prerelease: false
          title: Latest Release
          files: ./dist/**
